set dotenv-load

app            := "thane-agent-macos"
build-dir      := "build"
notary-profile := env("NOTARYTOOL_PROFILE", "notarytool")
deploy-path    := env("DEPLOY_PATH", "Applications")

export DEVELOPER_DIR := env("DEVELOPER_DIR", "/Applications/Xcode.app/Contents/Developer")

# List available recipes
default:
    @just --list

# --- Build ---

# Build for local development
[group('build')]
build: stamp
    xcodebuild -scheme {{app}} -destination 'platform=macOS' build

# Archive for distribution (auto-increments build number)
[group('build')]
archive: stamp
    rm -rf {{build-dir}}
    agvtool next-version -all
    xcodebuild archive \
        -scheme {{app}} \
        -destination 'generic/platform=macOS' \
        -archivePath {{build-dir}}/{{app}}.xcarchive

# Generate BuildInfo.swift with compile-time constants
[group('build')]
[private]
stamp:
    #!/usr/bin/env bash
    set -euo pipefail
    out="{{app}}/App/BuildInfo.swift"
    commit="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    dirty=""
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then dirty="-dirty"; fi
    cat > "$out" <<SWIFT
    // Generated by \`just stamp\` — do not edit.
    enum BuildInfo {
        static let gitCommit = "${commit}${dirty}"
        static let gitBranch = "${branch}"
        static let buildTimestamp = "${timestamp}"
    }
    SWIFT

# Export Developer ID-signed .app from archive
[group('build')]
export: archive
    xcodebuild -exportArchive \
        -archivePath {{build-dir}}/{{app}}.xcarchive \
        -exportPath {{build-dir}}/export \
        -exportOptionsPlist ExportOptions.plist
    @echo "Exported: {{build-dir}}/export/{{app}}.app"

# Clean build artifacts
[group('build')]
clean:
    rm -rf {{build-dir}}

# --- Test ---

# Build and run unit tests
[group('test')]
test:
    xcodebuild test \
        -scheme {{app}} \
        -destination 'platform=macOS'

# --- CI ---

# Full local CI gate — run before every push
[group('ci')]
ci: build test

# --- Release ---

# Notarize and staple the exported .app (runs export first)
[group('release-engineering')]
notarize: export
    ditto -c -k --keepParent \
        {{build-dir}}/export/{{app}}.app \
        {{build-dir}}/{{app}}-notarize.zip
    xcrun notarytool submit {{build-dir}}/{{app}}-notarize.zip \
        --keychain-profile "{{notary-profile}}" \
        --wait
    xcrun stapler staple {{build-dir}}/export/{{app}}.app
    @echo "Notarized and stapled."

# Deploy notarized .app to a remote macOS host via rsync
[doc("Operator path: build, notarize, and deploy the companion app to a remote host")]
[group('deploy')]
deploy-agent-macos host deploy_path=deploy-path: notarize
    #!/usr/bin/env bash
    set -euo pipefail
    host="{{host}}"
    app="{{app}}"
    deploy_path="{{deploy_path}}"
    build_dir="{{build-dir}}"

    echo "Stopping ${app} on ${host}..."
    ssh "$host" "pkill -x '${app}' 2>/dev/null || true"
    sleep 2

    echo "Deploying to ${host}:~/${deploy_path}/${app}.app..."
    ssh "$host" "mkdir -p '${deploy_path}' && rm -rf '${deploy_path}/${app}.app'"
    rsync -av \
        "${build_dir}/export/${app}.app" \
        "${host}:${deploy_path}/"
    echo "Deployed."

    echo "Starting ${app} on ${host}..."
    ssh "$host" "open '${deploy_path}/${app}.app'"
    echo "Done."
