# Don't echo each command line before running it — recipes emit their own
# status and the underlying tools (xcodebuild, etc.) print their own output, so
# the default interactive experience stays clean. Use `just --verbose <recipe>`
# to see the raw commands when debugging.
set quiet
set dotenv-load

app               := "thane-agent-macos"
build-dir         := "build"
deploy-path       := env("DEPLOY_PATH", "Applications")

# Release-engineering credentials — sourced from the environment. Names match
# the thane-ai-agent release scripts so both projects can share one .env file.
#   THANE_NOTARY_PROFILE    — keychain credential profile for `xcrun notarytool`
#   THANE_CODESIGN_IDENTITY — Developer ID Application identity (from `security find-identity`)
notary-profile    := env("THANE_NOTARY_PROFILE", env("NOTARYTOOL_PROFILE", ""))
signing-identity  := env("THANE_CODESIGN_IDENTITY", "")

export DEVELOPER_DIR := env("DEVELOPER_DIR", "/Applications/Xcode.app/Contents/Developer")

# List available recipes
default:
    @echo "Common workflows:"
    @echo "    just ci                                                   # full local gate (build + test) — run before pushing"
    @echo "    just release-github <version> [auto|prerelease|release]   # cut a release (DMG, notarize, GitHub)"
    @echo "    just deploy-macos <user@host>...                          # build, notarize, and deploy the app to macOS hosts"
    @echo ""
    @just --list

# --- Version ---

[doc("Print the marketing version (from the nearest git tag)")]
[group('version')]
marketing-version:
    #!/usr/bin/env bash
    tag="$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)"
    printf '%s\n' "${tag#v}"

[doc("Print the build number (git commit count)")]
[group('version')]
build-number:
    git rev-list --count HEAD 2>/dev/null || echo 0

[doc("Print the full version string baked into the app (git describe + dirty flag)")]
[group('version')]
describe:
    git describe --tags --always --dirty 2>/dev/null || echo dev

# --- Build ---

[doc("Build the app for local development (honors CODE_SIGNING_ALLOWED=NO for CI)")]
[group('build')]
build: stamp
    #!/usr/bin/env bash
    set -euo pipefail
    marketing="$(just marketing-version)"
    build_num="$(just build-number)"
    args=(
        -scheme "{{app}}"
        -destination 'platform=macOS'
        "MARKETING_VERSION=$marketing"
        "CURRENT_PROJECT_VERSION=$build_num"
    )
    if [ "${CODE_SIGNING_ALLOWED:-YES}" = "NO" ]; then
        args+=(
            "CODE_SIGN_IDENTITY=-"
            "CODE_SIGNING_REQUIRED=NO"
            "CODE_SIGNING_ALLOWED=NO"
        )
    fi
    xcodebuild "${args[@]}" build

[doc("Remove build artifacts")]
[group('build')]
clean:
    rm -rf "{{build-dir}}"

# Generate BuildInfo.swift with compile-time constants (git describe et al).
[private]
stamp:
    #!/usr/bin/env bash
    set -euo pipefail
    out="{{app}}/App/BuildInfo.swift"
    version="$(just describe)"
    commit="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    builder="$(whoami)@$(hostname -s)"
    cat > "$out" <<SWIFT
    // Generated by \`just stamp\` — do not edit.
    enum BuildInfo {
        static let version = "${version}"
        static let gitCommit = "${commit}"
        static let gitBranch = "${branch}"
        static let buildTimestamp = "${timestamp}"
        static let builtBy = "${builder}"
    }
    SWIFT

# Building block: archive for distribution. Version comes from the nearest git tag.
[private]
archive: stamp
    #!/usr/bin/env bash
    set -euo pipefail
    marketing="$(just marketing-version)"
    build_num="$(just build-number)"
    rm -rf "{{build-dir}}/{{app}}.xcarchive"
    xcodebuild archive \
        -scheme {{app}} \
        -destination 'generic/platform=macOS' \
        -archivePath "{{build-dir}}/{{app}}.xcarchive" \
        MARKETING_VERSION="$marketing" \
        CURRENT_PROJECT_VERSION="$build_num"

# Building block: export a Developer ID-signed .app from the archive. Generates
# an ExportOptions plist from THANE_CODESIGN_IDENTITY so the team ID never gets
# checked into the repo.
[private]
export: archive
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -z "{{signing-identity}}" ]; then
        echo "THANE_CODESIGN_IDENTITY is not set — required for signed exports." >&2
        echo "Example: 'Developer ID Application: Your Name (TEAMID1234)'" >&2
        exit 1
    fi
    team_id="$(printf '%s' "{{signing-identity}}" | sed -E 's/.*\(([A-Z0-9]+)\).*/\1/')"
    if [ -z "$team_id" ] || [ "$team_id" = "{{signing-identity}}" ]; then
        echo "Could not extract team ID from THANE_CODESIGN_IDENTITY." >&2
        exit 1
    fi
    rm -rf "{{build-dir}}/export"
    export_plist="{{build-dir}}/ExportOptions.plist"
    mkdir -p "{{build-dir}}"
    cat > "$export_plist" <<EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>method</key>
        <string>developer-id</string>
        <key>teamID</key>
        <string>${team_id}</string>
        <key>signingStyle</key>
        <string>automatic</string>
    </dict>
    </plist>
    EOF
    xcodebuild -exportArchive \
        -archivePath "{{build-dir}}/{{app}}.xcarchive" \
        -exportPath "{{build-dir}}/export" \
        -exportOptionsPlist "$export_plist"
    echo "Exported: {{build-dir}}/export/{{app}}.app"

# --- Test ---

[doc("Build and run the unit tests (same signing behavior as `just build`)")]
[group('test')]
test:
    #!/usr/bin/env bash
    set -euo pipefail
    args=(
        -scheme "{{app}}"
        -destination 'platform=macOS'
    )
    if [ "${CODE_SIGNING_ALLOWED:-YES}" = "NO" ]; then
        args+=(
            "CODE_SIGN_IDENTITY=-"
            "CODE_SIGNING_REQUIRED=NO"
            "CODE_SIGNING_ALLOWED=NO"
        )
    fi
    xcodebuild "${args[@]}" test

# --- CI ---

[doc("Full local CI gate (build + test) — run before every push")]
[group('ci')]
ci: build test

# --- Release engineering ---

# Building block: notarize and staple the exported .app. Uses a submission zip
# (notarytool doesn't accept raw .app bundles).
[private]
notarize-app: export
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -z "{{notary-profile}}" ]; then
        echo "THANE_NOTARY_PROFILE is not set — required for notarization." >&2
        exit 1
    fi
    ditto -c -k --keepParent \
        "{{build-dir}}/export/{{app}}.app" \
        "{{build-dir}}/{{app}}-notarize.zip"
    xcrun notarytool submit "{{build-dir}}/{{app}}-notarize.zip" \
        --keychain-profile "{{notary-profile}}" \
        --wait
    xcrun stapler staple "{{build-dir}}/export/{{app}}.app"
    echo "Notarized and stapled: {{build-dir}}/export/{{app}}.app"

# Building block: produce a signed, notarized, stapled DMG from the notarized .app.
[private]
dmg: notarize-app
    #!/usr/bin/env bash
    set -euo pipefail
    version="$(just marketing-version)"
    dmg_path="$(scripts/build-dmg.sh \
        "$version" \
        "{{build-dir}}/export/{{app}}.app" \
        "{{build-dir}}/release" \
        "{{signing-identity}}")"
    echo "Submitting DMG for notarization..."
    xcrun notarytool submit "$dmg_path" \
        --keychain-profile "{{notary-profile}}" \
        --wait
    xcrun stapler staple "$dmg_path"
    echo "DMG ready: $dmg_path"

# Building block: write {app}_{version}_checksums.txt alongside release assets.
[private]
checksums:
    #!/usr/bin/env bash
    set -euo pipefail
    version="$(just marketing-version)"
    release_dir="{{build-dir}}/release"
    if [ ! -d "$release_dir" ]; then
        echo "No release directory at $release_dir — run 'just dmg' first" >&2
        exit 1
    fi
    shopt -s nullglob
    cd "$release_dir"
    artifacts=("{{app}}_${version}".dmg)
    if [ "${#artifacts[@]}" -eq 0 ]; then
        echo "No release artifacts found in $release_dir" >&2
        exit 1
    fi
    output="{{app}}_${version}_checksums.txt"
    shasum -a 256 "${artifacts[@]}" > "$output"
    echo "Wrote $release_dir/$output"
    cat "$output"

# Build + notarize the DMG and checksums locally, without tagging or publishing.
# Stops at a reviewable breakpoint: inspect build/release/, then `publish-release`.
# Mirrors thane-ai-agent's prepare-release (names are shared; this DMG/notarize
# implementation is ours).
[doc("Prepare a release locally for VERSION: CI, tag, build notarized DMG + checksums (no push)")]
[group('release-engineering')]
prepare-release version:
    #!/usr/bin/env bash
    set -euo pipefail
    version="{{version}}"
    version="${version#v}"
    tag="v${version}"

    if ! printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$'; then
        echo "Version must look like 0.1.0 or 0.1.0-rc.1" >&2
        exit 1
    fi

    # Preflight: release-engineering env vars present.
    if [ -z "{{signing-identity}}" ]; then
        echo "THANE_CODESIGN_IDENTITY is not set — required for signed releases." >&2
        exit 1
    fi
    if [ -z "{{notary-profile}}" ]; then
        echo "THANE_NOTARY_PROFILE is not set — required for notarization." >&2
        exit 1
    fi

    # Preflight: on main, clean tree, HEAD already on origin/main (releases ship
    # from merged commits, never push code).
    branch="$(git rev-parse --abbrev-ref HEAD)"
    if [ "$branch" != "main" ]; then
        echo "Not on main (current: $branch) — releases ship from main." >&2
        exit 1
    fi
    if ! git diff --quiet HEAD -- || ! git diff --cached --quiet -- ; then
        echo "Working tree has uncommitted changes — commit or stash before releasing." >&2
        exit 1
    fi
    git fetch --quiet origin main
    if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
        echo "HEAD does not match origin/main — merge release commits via PR first." >&2
        exit 1
    fi

    # Tag locally (not pushed). Re-preparing the exact same commit is allowed —
    # but only when the existing tag is the annotated/signed tag we create, never
    # a stray lightweight tag (which would publish unsigned, defeating 'git tag -s').
    if git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
        if [ "$(git cat-file -t "$tag")" != "tag" ]; then
            echo "Tag $tag exists but is not an annotated tag — delete it and re-run (releases use 'git tag -s')." >&2
            exit 1
        fi
        if [ "$(git rev-parse "${tag}^{commit}")" != "$(git rev-parse HEAD)" ]; then
            echo "Tag $tag already exists at a different commit — delete it or pick a new version." >&2
            exit 1
        fi
        echo "==> Tag $tag already exists at HEAD (annotated) — re-preparing."
    fi

    # Gate: full CI must pass.
    echo "==> Running CI gate..."
    just ci

    # Tag before building so git describe bakes the tag into the artifact.
    if ! git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
        echo "==> Tagging $tag..."
        git tag -s "$tag" -m "Release $tag"
    fi

    # Build the notarized DMG (archive → export → notarize .app → DMG → notarize → staple).
    echo "==> Building notarized DMG..."
    just dmg

    echo "==> Writing checksums..."
    just checksums

    # Handoff metadata: publish-release verifies it's publishing exactly what was
    # prepared from this commit.
    mkdir -p "{{build-dir}}"
    meta="{{build-dir}}/.{{app}}_${version}_prepared.env"
    {
        printf 'PREPARED_VERSION=%s\n' "$version"
        printf 'PREPARED_COMMIT=%s\n' "$(git rev-parse HEAD)"
    } > "$meta"

    echo ""
    echo "==> Prepared $tag (local tag, not pushed). Inspect {{build-dir}}/release/, then:"
    echo "      just publish-release $version"
    echo "    To abort:  git tag -d $tag"

# Publish an already-prepared release: verify the prepared artifacts match HEAD,
# push the tag, and create the GitHub release. release_kind: auto (default,
# prerelease inferred from a pre-release version), prerelease, or release.
[doc("Publish a prepared release for VERSION: push tag + GitHub release (run prepare-release first)")]
[group('release-engineering')]
publish-release version release_kind="auto":
    #!/usr/bin/env bash
    set -euo pipefail
    version="{{version}}"
    version="${version#v}"
    tag="v${version}"
    release_kind="{{release_kind}}"

    meta="{{build-dir}}/.{{app}}_${version}_prepared.env"
    if [ ! -f "$meta" ]; then
        echo "No prepared release for $version — run 'just prepare-release $version' first." >&2
        exit 1
    fi
    # shellcheck disable=SC1090
    . "$meta"

    head_commit="$(git rev-parse HEAD)"
    if [ "${PREPARED_VERSION:-}" != "$version" ]; then
        echo "Prepared metadata is for '${PREPARED_VERSION:-}', not '$version' — re-run prepare-release." >&2
        exit 1
    fi
    if [ "${PREPARED_COMMIT:-}" != "$head_commit" ]; then
        echo "Prepared from ${PREPARED_COMMIT:-?}, but HEAD is $head_commit — re-run prepare-release." >&2
        exit 1
    fi
    if ! git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
        echo "Tag $tag is missing — run 'just prepare-release $version'." >&2
        exit 1
    fi
    if [ "$(git cat-file -t "$tag")" != "tag" ]; then
        echo "Tag $tag is not an annotated tag — re-run 'just prepare-release $version'." >&2
        exit 1
    fi
    if [ "$(git rev-parse "${tag}^{commit}")" != "$head_commit" ]; then
        echo "Tag $tag points at a different commit than HEAD ($head_commit) — re-run 'just prepare-release $version'." >&2
        exit 1
    fi
    if ! git diff --quiet HEAD -- || ! git diff --cached --quiet -- ; then
        echo "Working tree has uncommitted changes — commit or stash before publishing." >&2
        exit 1
    fi

    release_dir="{{build-dir}}/release"
    dmg_path="${release_dir}/{{app}}_${version}.dmg"
    checksum_path="${release_dir}/{{app}}_${version}_checksums.txt"
    for asset in "$dmg_path" "$checksum_path"; do
        if [ ! -f "$asset" ]; then
            echo "Missing prepared asset: $asset — run 'just prepare-release $version'." >&2
            exit 1
        fi
    done

    case "$release_kind" in
        auto)       prerelease_flag=""; case "$version" in *-*) prerelease_flag="--prerelease" ;; esac ;;
        prerelease) prerelease_flag="--prerelease" ;;
        release)    prerelease_flag="" ;;
        *) echo "release_kind must be auto, prerelease, or release (got '$release_kind')." >&2; exit 1 ;;
    esac

    # Push the tag only — commits must already be on origin/main.
    echo "==> Pushing tag $tag..."
    git push origin "$tag"

    # GitHub release — notes auto-generated from merged PRs + commits since the
    # previous tag.
    echo "==> Creating GitHub release..."
    gh release create "$tag" \
        --title "$tag" \
        --generate-notes \
        $prerelease_flag \
        "$dmg_path" \
        "$checksum_path"

    echo "==> Released $tag"

# Cut a full release for VERSION end-to-end: prepare (CI, tag, DMG, checksums)
# then publish (push tag, GitHub release). Release notes auto-generated from PRs
# and commits since the last tag. release_kind: auto (default), prerelease, release.
[doc("Cut a release for VERSION (e.g. 0.1.0): prepare + publish in one step")]
[group('release-engineering')]
release-github version release_kind="auto":
    just prepare-release "{{version}}"
    just publish-release "{{version}}" "{{release_kind}}"

# --- Deploy ---

[arg("deploy_path", long="deploy-path")]
[doc("Build and notarize once, then deploy the app to one or more user@host targets")]
[group('deploy')]
[positional-arguments]
deploy-macos deploy_path=deploy-path +hosts: notarize-app
    #!/usr/bin/env bash
    set -euo pipefail
    deploy_path="$1"
    shift
    hosts=("$@")
    app="{{app}}"
    build_dir="{{build-dir}}"
    version="$(just describe)"
    # Both SSH and rsync pass remote paths through the remote login shell.
    printf -v remote_deploy_path '%q' "$deploy_path"
    printf -v remote_app_path '%q' "${deploy_path}/${app}.app"

    for host in "${hosts[@]}"; do
        echo "Stopping ${app} on ${host}..."
        ssh "$host" "pkill -x '${app}' 2>/dev/null || true"
        sleep 2

        echo "Deploying to ${host}:${deploy_path}/${app}.app..."
        ssh "$host" "mkdir -p ${remote_deploy_path} && rm -rf ${remote_app_path}"
        rsync -av \
            "${build_dir}/export/${app}.app" \
            "${host}:${remote_deploy_path}/"

        echo "Starting ${app} on ${host}..."
        ssh "$host" "open ${remote_app_path}"

        echo "Deployed version: ${version} -> ${host}"
    done
